services:
  - type: web
    name: maths-hw-iterative-method
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000