services:
  - type: web
    name: maths-hw-iterative-method
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/index.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9